import type { Metadata } from "next";
import { Manrope } from 'next/font/google';  
import "./globals.css";
import { cn } from "@/lib/utils";
import Footer from "@/components/footer";


const manrope = Manrope({
  subsets: ['latin'],
  variable: '--font-manrope', 
  weight: ['200', '300', '400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: "Boldo Apps",
  description: "Generated by Boldo Apps",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `${manrope.variable} relative h-full font-sans antialiased`  
        )}
      >
        <main className="relative flex flex-col min-h-screen ">
          {/* <Navbar /> */}
          <div className="flex-grow flex-1">{children}</div>
          <Footer />
        </main>
      </body>
    </html>
  );
}