import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import Footer from "@/components/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Boldo Apps",
  description: "Generated by Boldo Apps",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `${geistSans.variable} ${geistMono.variable} relative h-full font-sans antialiased`
        )}
      >
        <main className="relative flex flex-col min-h-screen ">
          {/* <Navbar /> */}
          <div className="flex-grow flex-1">{children}</div>
          <Footer />
        </main>
        {/* {children} */}
      </body>
    </html>
  );
}
